// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtpXcwGcjBEb3KDZB8KO1gzcR_HRTEWkg',
    appId: '1:468760344655:web:25fa666942f4ce5cb1d23a',
    messagingSenderId: '468760344655',
    projectId: 'meowssenger-chat-app',
    authDomain: 'meowssenger-chat-app.firebaseapp.com',
    storageBucket: 'meowssenger-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZxfQEqVqH1_FbZfjM3sniRIyDTJLOHQk',
    appId: '1:468760344655:android:7a4b4c08dec44c1ab1d23a',
    messagingSenderId: '468760344655',
    projectId: 'meowssenger-chat-app',
    storageBucket: 'meowssenger-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsfsNmhND43NhzMPtTx6MDsAXyW_IviOI',
    appId: '1:468760344655:ios:9333a08a9f283d2ab1d23a',
    messagingSenderId: '468760344655',
    projectId: 'meowssenger-chat-app',
    storageBucket: 'meowssenger-chat-app.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsfsNmhND43NhzMPtTx6MDsAXyW_IviOI',
    appId: '1:468760344655:ios:6906f38067733702b1d23a',
    messagingSenderId: '468760344655',
    projectId: 'meowssenger-chat-app',
    storageBucket: 'meowssenger-chat-app.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
